// These are the presets from rizal72
//  ref: https://forums.frontier.co.uk/showthread.php?t=195658&p=3043570&viewfull=1#post3043570
var presets = {
	"ADDER":
		"BTCQEQ BTEQFQ BTFQEU BTFQDV BTDVCV CQCNDM CQDMDQ DMHIMG DMGMDQ DQGMFQ EUFQHP EUHPKN EUKNPM EUPMIU EUIUGV"
		 + "EUGVDV FQGMHP GMHIJH GMJHNF GMNFPF GMPFJL GMJLKN HIIGJH PJLKNN IGLEMF IGMFJH IUPMQO JHNFNF JLPFPG JLPGSG"
		 + "JLSGKN KNSGPM PFQDPG PGQDSD PGSDSG PMSGVH PMVHVM PMVMQO SDTBSG SGTBTF SGTFVH VHXGVM VMXGYI XGYEYI",

	"ANACONDA":
		"NALBOB JGLBMG KIJGKM HPKMJS HTKSIW HWKSJZ JZKSMZ MTPZPS MZPSPZ KSNJLB LBOBNJ OBSPQS NJOBRT RSSTSV NJPSOZ"
		+ "SVQZPZ NJPSPLS",

	"ASP":
		"AODJHM AOHMQT DJFIHM EHHHII EHIIFI FIIIHM HHJGKG HHKGNG HHNGMH HHMHII HMIILI HMLISR HMSRQT IIMHLI KFNGKG"
		+ "LIMHWQ LIWQUQ LIUQSR MHNGOG MHOGWQ OGVIZN OGZNYO STSRST URUQST STUQUR UQWQWR UQWRVS UQVSUR WQYOYP WQYPWR",

	"COBRA":
		"FCAJBM FCHHBM FCLBHH BMHHHO LBHHQP HHHOQP LBQPVL QPVLWP",

	"DBS":
		"BUCQEV BUEVEX BUEXBW CQFNFR CQFREV EKIIGJ EVFRHT EVHTHV EVHVEX FNGKHL FNHLIO FNIOFR FRIOIQ FRIQHT GKIILM GKLMHL"
		+ "HLLMKM HLKMIO HTIQIT HTITIW HTIWHV HVIWHW IIMGNK IINKLM IOKMIQ IQKMIS ISKMLM ISLMMR ISMRMS ISMSIW IWMSLV LMNKON"
		+ "LMONMR MGTDSF MGSFRH MGRHNK MRONOP MROPMS MSOPPP MSPPPR NKRHPM NKPMON ONPMPO ONPOOP OPPOPP PMRHVK PMVKZP PMZPXS"
		+ "PMXSPO POXSPP PPXSPR RHSFVF RHVFYI RHYIYJ RHYJVK VFXEYI",

	"DBX":
		"BOCMCQ BOCQCS BOCSBQ CMFKDO CMDOCQ CQDOFP CQFPGR CQGRCS DOFKGL DOGLHN DOHNFP FKHIGL FPHNJO FPJOJP FOJPGR GLHIKK"
		+ "GLKKHN GRJPJR HIMGKK HNKKNM HNNMJO JONMNN JONNJP JPNNNP JPNPJR KKMGOI KKOINM MFPEOG MFOGOH MFOHMG MGOHOI NMOIPK"
		+ "NMPKPN NMPNNN NNPNOP NNOPNP OGPESE OGSEQI OGQIOH OHQIOI OIQIPK OPPNQO PEUDSE PKQIXI PKXIWK PKWKZN PKZNWQ PKWQQO"
		+ "QISEXI SEUDVE SEVEZH SEZHXI UDVCVE VEXEZH XEZDZH XIZHZI",

	"COURIER":
		"AQHLHM AQHLHM AQGOHO AQGOMO GKGJHL GKCKEJ BJCICK CIIGGJ IGKFLG JHLGKH GJKIMJ MJSHVK SHVIVK LLMJVK BRLLMO"
		+ "BRMOLQ LLVKMO LQMORP LQQRRP PTPVQU PTXPYR QUYRXP PVPVXS QUYQXS QRRPVQ RPUOVQ MOVKYM VKXJYM MOUOYM ",

	"CLIPPER":
		"AQBPDN ARFQGR CQDOEP DNKKHN FLNIGM FLFJNI FJFINI FIHHJH CICHDH CHFFDH DHFFIF FFIEIF HHIGJH KKRHRI KKRIMN MNRISJ "
		+ "FQMNGR GRMNLQ LQTLPP LQPPOR ORTLQS QSTMRS SSTMTT TMULUM URVSTT SVTUTV TUXRYS TUTVYS XRZSYS TVXUZS ",

	"EAGLE":
		"CMCRKO DRKNMY KNLDMK LDMAOD ODMKQN MKMYQN MYQNXR QNXRXM ",

	"DROPSHIPS":
		"AOFKHK FKFIHK FIHHHK HKHHKI HHJGLI JGNGKH FMGKJN HKLIJN JNLIRH GNFQHO IPJNJP GTIPJT IPJNMS INNKMT MTNIYR "
		+ "NKZPYS NKRHZP",

	"FDL":
		"ATKIJM KILGMI JMKINH NHPFOI OITIQJ TIVITJ VIXGWI UKUIWI UKWIWJ ROUJXL WLZMUO BUROWO BUIMTJ BUTKRO KLNNRJ NIQNQJ ",

	"HAULER":
		"ASAOHP AOEKHP DKKLAO DKJGHK JGKFLG JGNGHK NGRHHK RHKLHK RHSFTI RHRNKL TIVMZN VMSPRN KLRNFQ CSRNSP ASHPCS",

	"ORCA":
		"CDFCFE CDFEEF CDEFGK CDGKCF CFGKEI CFEIDH CHDHEI CHEIDI EFFEGF EFGFIH EFIHIJ EFIJHK EFHKGK FCIDFE FEIDGF GFIDKI "
		+ "GFKIIH GKHKJM HKIJJM IDNHKI IHKIKJ IHKJIJ JKJJMO JMKJOM JMOMTT JMTTTU JMTUTV JMTVPS JPLPPS JPPSLR JMPSLP KINHOM "
		+ "KIOMKJ NHRLOM OMRLUQ OMUQTT TTUQVU TTVUTU TUVUWW TUWWTV UQVQXT UQXTXU UQXUVU VUXUWW WXXUXW XTYVXU XUYVXW ",

	"PYTHON":
		"FAGAHG GAICHG HAMFHC ICMFJE JEMFKG JFKGJG MFNKRM NKRMTS LKTSPP PPTSTU PPTURX PPRXNU NURXOZ NUQZMX JPPPNU "
		+ "HGMKLO MKPPLO HGLOIP GHKPIP ",

	"SW":
		"ACNALC LCNAPC NAZCPC ACLCDL DLNAWL PCZCWL LEPEMG",

	"T6":
		"CIEGON CIONEL CIELCO COELIP COIPHR COHRCQ CQHRHU EEEFGG EEGGFG EEFGEG EGEFON ELONIP FGGGON HRIPKS HRKSKT HRKTHU "
		+ "HUKTJV IPONOQ IPOQKS KDKLKF KFLDMF KFMFQH KFQHMI MFRFXJ MIQHQM MIQMON ONQMSQ OQSQSS OQSSRT QHXJUL QHULQM QMULSQ "
		+ "RTSSUS SQULVP SQVPVR SQVPSS SSVRUS ULXJXM ULXMVP XJYKXM XMYKYO ",

	"T7":
		"BVARGV ARAOEJ EJQIJL EJKHQI LMMGNG MGPERE NGRESF MHSFQI SFUFVG SFVGQI TIVGTJ JLTISK SKVIUL ULVIYG ULYGIP JLSKKO "
		+ "IOJLKO GQIOKO ETGQMT ETMTGV KOMQLR LRRRMT LRRPRR RRSPVR SPWPVR RPUNSP TNWLWN WNWLYN WLZMYN ULVIYG ULYGYI ",

	"T9":
		"ANDPBP AMBLDN BIGKCK BIQNGL BICFGK CFGELH IFLELH LFPILH LFOHMH PHPFSG SGVGSH SHVGZN PHSGUL TGZNVJ MHIJLK MHQHPI "
		+ "LHPILK LKPIUL LKULQO ULYNYR TMYQUT YRYTVU VTYRVU RNVUPT MORNPT IPMOPT MRPTNU JPNUKT JBIPKT ",

	"VIPER":
		"ANCKEL ANELEP CKEHEL EHJKEL EHFGJK EPJKVU JKWTVU FGOLON OLONRP RPTPVS QLYQWQ YOYQQL FGGFQL FGQLOL HGIFQL IFKFQL "
		+ "KFQLYO KFOFYO ",

	"VULTURE":
		"APCJKR APKRER APERDR CJDIGJ CJGJPN CJPNKM CJKMKR ERKRLS ERLSGT FGGFHH GFKCOJ GFOJQL GFQLHH GJHHPM GJPMPN HHQLPM "
		+ "KCNDOJ KMPNMN KMMNKR KRMNNS KRNSLS MNPNQO MNQOSQ MNSQNS NDQGOJ NSSQOT OJQGQH OJQHSL OJSLQL OTQLVT PMQLRM PMRMQO "
		+ "PMQOPN PUVTVU QHTISL QLSLRM QORMUO QOUOSQ RMSLUO SLTIUI SLUIYN SLYNWN SQUOUR SQURVT UOWNYQ UOYQXR UOXRUR URWSVT "
		+ "VTWSWT VTWTVU"
};
